### ISSUE TITLE
Proposal autodetecting actual columns

### ISSUE THREAD

**Issue by davidjr82** [archtechx/virtualcolumn#20]
Hello!

I was testing this package as I am testing the great tenancy package.

The only thing that bothers me a bit is having to specify the actual columns of the model where I want to use this trait. I ended up using this in my own trait, so any real column is not included in the data column:

```php
public static function getCustomColumns(): array
{
    return \Illuminate\Support\Facades\Schema::getColumnListing((new static)->getTable());
}
```

Is this something that makes sense to add by default in this package, instead of a default ['id'] array?

**Comment by stancl** [comment]
Wouldn't `getColumnListing()` run a SQL query each time this method is called?

**Comment by davidjr82** [comment]
Yes, but it can be cached (I do it with 24hr or whenever I run migrations, so for me it is only one query per day and model).

I am using the package to allow my customers to add dynamic columns. If it would be only for the tenancy package, then it's not worth it.

So if the scope of the package is intended only for tenancy, I would reject the idea. But if it is a wider scope, then I think it is valuable to consider it.

**Comment by stancl** [comment]
I think the columns should be defined statically. That way they can be versioned along with migrations and we avoid the entire rabbit hole of:
- not being able to use deserialized models unless the connection is also instantiated
- configurable cache TTLs
- something going wrong in the schema and this code starting to misbehave

If you want to get the column list dynamically from the database, you can extend the method like you have.
